version: '3.1'

services:
  shop:
  bank:
  postgres:
    image: postgres
    restart: always
    enviroment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=onlineshop
    volumes: 
      - ./postgres:/var/lib/postresql/data
    ports: 
      - 5432:5432
  mysql:
